name: fluttergraphqlsample
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # Architecture
  state_notifier: ^0.6.0
  flutter_state_notifier: ^0.6.1
  provider: ^4.3.2

  # API
  graphql_flutter: ^3.1.0
  artemis: 6.6.4-beta.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.1
  freezed: any
  json_serializable: any

flutter:

  uses-material-design: true
